<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\CommunityToolkit.Embeddings.Onnx\CommunityToolkit.Embeddings.Onnx.csproj" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" />
  </ItemGroup>
</Project>
