<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <ProjectReference Include="../../src/CommunityToolkit.Embeddings.Onnx/CommunityToolkit.Embeddings.Onnx.csproj" />
    <None Update="Fixtures/*.onnx" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Fixtures/bert-regression-vocab.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>